CREATE TABLE KEYWORDS(
ID int NOT NULL AUTO_INCREMENT,
NAME nvarchar(2048) NOT NULL,
PERSON_ID int,
CONSTRAINT fk_persons
    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSONS(ID)
);

CREATE TABLE PERSONS(
ID int NOT NULL AUTO_INCREMENT,
NAME nvarchar(2048) NOT NULL ,
CONSTRAINT persons_pk PRIMARY KEY (ID)
);

CREATE TABLE PAGES(
ID long NOT NULL AUTO_INCREMENT,
URL varchar(2048) NOT NULL,
SITE_ID int,
FOUND datetime NOT NULL,
LAST_SCAN datetime NOT NULL,
CONSTRAINT fk_sites
    FOREIGN KEY (SITE_ID)
    REFERENCES SITES(ID),

CONSTRAINT pages_pk PRIMARY KEY (ID)
);

CREATE TABLE SITES(
ID int NOT NULL AUTO_INCREMENT,
NAME varchar(256) NOT NULL,
CONSTRAINT sites_pk PRIMARY KEY (ID)
);

CREATE TABLE PERSON_PAGE_RANK(
PERSON_ID int,
PAGE_ID int,
RANK int NOT NULL,
CONSTRAINT fk_pages_rank
    FOREIGN KEY (PAGE_ID)
    REFERENCES PAGES(ID),

CONSTRAINT fk_persons_rank
    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSONS(ID)
);