CREATE TABLE KEYWORDS(
ID int,
NAME nvarchar(2048),
PERSON_ID int,
CONSTRAINT fk_persons
    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSONS(ID)
);

CREATE TABLE PERSONS(
ID int,
NAME nvarchar(2048),
CONSTRAINT persons_pk PRIMARY KEY (ID)
);

CREATE TABLE PAGES(
ID long,
URL varchar(2048),
SITE_ID int,
FOUND datetime,
LAST_SCAN datetime,
CONSTRAINT fk_sites
    FOREIGN KEY (SITE_ID)
    REFERENCES SITES(ID),

CONSTRAINT pages_pk PRIMARY KEY (ID)
);

CREATE TABLE SITES(
ID int,
NAME varchar(256),
CONSTRAINT sites_pk PRIMARY KEY (ID)
);

CREATE TABLE PERSON_PAGE_RANK(
PERSON_ID int,
PAGE_ID int,
RANK int,
CONSTRAINT fk_pages_rank
    FOREIGN KEY (PAGE_ID)
    REFERENCES PAGES(ID),

CONSTRAINT fk_persons_rank
    FOREIGN KEY (PERSON_ID)
    REFERENCES PERSONS(ID)
);